public with sharing class APIEndPoints {
    public static final string AutoSearch = 'https://anypoint.mulesoft.com/mocking/api/v1/links/e38620e6-e325-4540-b559-4f885ad97232/employee/sys/v1/auto-search';
    public static final string EmployeeDetails = 'https://anypoint.mulesoft.com/mocking/api/v1/links/e38620e6-e325-4540-b559-4f885ad97232/employee/sys/v1/employee-details';
    public static final string ClaimLeaveList = 'https://anypoint.mulesoft.com/mocking/api/v1/links/e38620e6-e325-4540-b559-4f885ad97232/employee/sys/v1/claim-leave';
	public static final string ClaimDetails = 'https://anypoint.mulesoft.com/mocking/api/v1/links/e38620e6-e325-4540-b559-4f885ad97232/employee/sys/v1/claim-details';
	public static final string LeaveDetails = 'https://anypoint.mulesoft.com/mocking/api/v1/links/e38620e6-e325-4540-b559-4f885ad97232/employee/sys/v1/leave-details';
	public static final string Authorization = 'https://anypoint.mulesoft.com/mocking/api/v1/links/40930352-1007-455a-b14d-5f330f8dc7af/api/SearchByLastName';
}