public with sharing class APIEndPoints {
    public static final string AutoSearch = 'http://employees-cli-prc-api.us-e1.cloudhub.io/api/cli/employees/v1?searchBy=lastName&searchText=bb&userId=0&orgId=27232';
   // public static final string EmployeeDetails = 'https://anypoint.mulesoft.com/mocking/api/v1/links/e38620e6-e325-4540-b559-4f885ad97232/employee/sys/v1/employee-details';
    public static final string EmployeeDetails = 'https://anypoint.mulesoft.com/mocking/api/v1/links/e38620e6-e325-4540-b559-4f885ad97232/employee/sys/v1/employee-details';
    public static final string ClaimLeaveList = 'https://anypoint.mulesoft.com/mocking/api/v1/links/e38620e6-e325-4540-b559-4f885ad97232/employee/sys/v1/claim-leave';
	public static final string ClaimDetails = 'https://anypoint.mulesoft.com/mocking/api/v1/links/e38620e6-e325-4540-b559-4f885ad97232/employee/sys/v1/claim-details';
	public static final string LeaveDetails = 'https://anypoint.mulesoft.com/mocking/api/v1/links/e38620e6-e325-4540-b559-4f885ad97232/employee/sys/v1/leave-details';
	public static final string Authorization = 'https://anypoint.mulesoft.com/mocking/api/v1/links/40930352-1007-455a-b14d-5f330f8dc7af/api/SearchByLastName';
	public static final string CLISearchRelatedOrgLists ='https://anypoint.mulesoft.com/mocking/api/v1/links/40930352-1007-455a-b14d-5f330f8dc7af/api/SearchByLastName';
}