public with sharing class APIEndPoints {
    public static final string AutoSearch = 'https://anypoint.mulesoft.com/mocking/api/v1/links/40930352-1007-455a-b14d-5f330f8dc7af/api/SearchByLastName';
    public static final string EmployeeDetails = 'https://anypoint.mulesoft.com/mocking/api/v1/links/40930352-1007-455a-b14d-5f330f8dc7af/api/SearchByLastName';
    public static final string ClaimLeaveList = 'https://anypoint.mulesoft.com/mocking/api/v1/links/40930352-1007-455a-b14d-5f330f8dc7af/api/GetClaimLeave';
	public static final string ClaimDetails = 'https://anypoint.mulesoft.com/mocking/api/v1/links/40930352-1007-455a-b14d-5f330f8dc7af/api/GetClaimDetails';
	public static final string LeaveDetails = 'https://anypoint.mulesoft.com/mocking/api/v1/links/40930352-1007-455a-b14d-5f330f8dc7af/api/GetLeaveDetails';
	public static final string Authorization = 'https://anypoint.mulesoft.com/mocking/api/v1/links/40930352-1007-455a-b14d-5f330f8dc7af/api/SearchByLastName';
}